// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: candystore.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CandyStore_Buy_FullMethodName = "/candystore.CandyStore/Buy"
)

// CandyStoreClient is the client API for CandyStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CandyStoreClient interface {
	Buy(ctx context.Context, in *BuyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type candyStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewCandyStoreClient(cc grpc.ClientConnInterface) CandyStoreClient {
	return &candyStoreClient{cc}
}

func (c *candyStoreClient) Buy(ctx context.Context, in *BuyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CandyStore_Buy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CandyStoreServer is the server API for CandyStore service.
// All implementations must embed UnimplementedCandyStoreServer
// for forward compatibility
type CandyStoreServer interface {
	Buy(context.Context, *BuyRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedCandyStoreServer()
}

// UnimplementedCandyStoreServer must be embedded to have forward compatible implementations.
type UnimplementedCandyStoreServer struct {
}

func (UnimplementedCandyStoreServer) Buy(context.Context, *BuyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Buy not implemented")
}
func (UnimplementedCandyStoreServer) mustEmbedUnimplementedCandyStoreServer() {}

// UnsafeCandyStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CandyStoreServer will
// result in compilation errors.
type UnsafeCandyStoreServer interface {
	mustEmbedUnimplementedCandyStoreServer()
}

func RegisterCandyStoreServer(s grpc.ServiceRegistrar, srv CandyStoreServer) {
	s.RegisterService(&CandyStore_ServiceDesc, srv)
}

func _CandyStore_Buy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CandyStoreServer).Buy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CandyStore_Buy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CandyStoreServer).Buy(ctx, req.(*BuyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CandyStore_ServiceDesc is the grpc.ServiceDesc for CandyStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CandyStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "candystore.CandyStore",
	HandlerType: (*CandyStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Buy",
			Handler:    _CandyStore_Buy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "candystore.proto",
}
